services:
  # PostgreSQL databases (one per service)
  postgres-calculator:
    image: postgres:15-alpine
    container_name: greenledger-postgres-calculator
    environment:
      POSTGRES_DB: calculator_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_calculator_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d calculator_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-tracker:
    image: postgres:15-alpine
    container_name: greenledger-postgres-tracker
    environment:
      POSTGRES_DB: tracker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_tracker_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tracker_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-wallet:
    image: postgres:15-alpine
    container_name: greenledger-postgres-wallet
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_wallet_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wallet_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-userauth:
    image: postgres:15-alpine
    container_name: greenledger-postgres-userauth
    environment:
      POSTGRES_DB: userauth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - postgres_userauth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d userauth_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-reporting:
    image: postgres:15-alpine
    container_name: greenledger-postgres-reporting
    environment:
      POSTGRES_DB: reporting_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    volumes:
      - postgres_reporting_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d reporting_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-certifier:
    image: postgres:15-alpine
    container_name: greenledger-postgres-certifier
    environment:
      POSTGRES_DB: certifier_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5437:5432"
    volumes:
      - postgres_certifier_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d certifier_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: greenledger-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Kafka for event streaming
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: greenledger-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: greenledger-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Calculator Service
  calculator-service:
    build:
      context: .
      dockerfile: services/calculator/Dockerfile
    container_name: greenledger-calculator
    ports:
      - "8081:8081"
      - "9081:9081"
    environment:
      DB_HOST: postgres-calculator
      DB_PORT: 5432
      DB_NAME: calculator_db
      DB_USER: postgres
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BROKERS: kafka:9092
      SERVER_PORT: 8081
      GRPC_PORT: 9081
      JWT_SECRET: your-secret-key
      LOG_LEVEL: info
      ENVIRONMENT: development
    depends_on:
      postgres-calculator:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Tracker Service
  tracker-service:
    build:
      context: .
      dockerfile: services/tracker/Dockerfile
    container_name: greenledger-tracker
    ports:
      - "8082:8082"
      - "9082:9082"
    environment:
      DB_HOST: postgres-tracker
      DB_PORT: 5432
      DB_NAME: tracker_db
      DB_USER: postgres
      DB_PASSWORD: password
      KAFKA_BROKERS: kafka:9092
      SERVER_PORT: 8082
      GRPC_PORT: 9082
      JWT_SECRET: your-secret-key
      LOG_LEVEL: info
      ENVIRONMENT: development
    depends_on:
      postgres-tracker:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Wallet Service
  wallet-service:
    build:
      context: .
      dockerfile: services/wallet/Dockerfile
    container_name: greenledger-wallet
    ports:
      - "8083:8083"
      - "9083:9083"
    environment:
      DB_HOST: postgres-wallet
      DB_PORT: 5432
      DB_NAME: wallet_db
      DB_USER: postgres
      DB_PASSWORD: password
      KAFKA_BROKERS: kafka:9092
      SERVER_PORT: 8083
      GRPC_PORT: 9083
      JWT_SECRET: your-secret-key
      LOG_LEVEL: info
      ENVIRONMENT: development
    depends_on:
      postgres-wallet:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # User Auth Service
  user-auth-service:
    build:
      context: .
      dockerfile: services/user-auth/Dockerfile
    container_name: greenledger-user-auth
    ports:
      - "8084:8084"
      - "9084:9084"
    environment:
      DB_HOST: postgres-userauth
      DB_PORT: 5432
      DB_NAME: userauth_db
      DB_USER: postgres
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVER_PORT: 8084
      GRPC_PORT: 9084
      JWT_SECRET: your-secret-key
      LOG_LEVEL: info
      ENVIRONMENT: development
    depends_on:
      postgres-userauth:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8084/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Reporting Service
  reporting-service:
    build:
      context: .
      dockerfile: services/reporting/Dockerfile
    container_name: greenledger-reporting
    ports:
      - "8085:8085"
      - "9085:9085"
    environment:
      DB_HOST: postgres-reporting
      DB_PORT: 5432
      DB_NAME: reporting_db
      DB_USER: postgres
      DB_PASSWORD: password
      CALCULATOR_DB_HOST: postgres-calculator
      TRACKER_DB_HOST: postgres-tracker
      WALLET_DB_HOST: postgres-wallet
      SERVER_PORT: 8085
      GRPC_PORT: 9085
      JWT_SECRET: your-secret-key
      LOG_LEVEL: info
      ENVIRONMENT: development
    depends_on:
      postgres-reporting:
        condition: service_healthy
      postgres-calculator:
        condition: service_healthy
      postgres-tracker:
        condition: service_healthy
      postgres-wallet:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8085/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reporting.rule=PathPrefix(`/api/v1/reporting`)"
      - "traefik.http.services.reporting.loadbalancer.server.port=8085"

  # Certificate Service
  certifier-service:
    build:
      context: .
      dockerfile: services/certifier/Dockerfile
    container_name: greenledger-certifier
    ports:
      - "8086:8086"
      - "9086:9086"
    environment:
      DB_HOST: postgres-certifier
      DB_PORT: 5432
      DB_NAME: certifier_db
      DB_USER: postgres
      DB_PASSWORD: password
      SERVER_PORT: 8086
      GRPC_PORT: 9086
      JWT_SECRET: your-secret-key
      LOG_LEVEL: info
      ENVIRONMENT: development
    depends_on:
      postgres-certifier:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.certifier.rule=PathPrefix(`/api/v1/certificates`)"
      - "traefik.http.services.certifier.loadbalancer.server.port=8086"

  # API Gateway (Traefik)
  traefik:
    image: traefik:v3.0
    container_name: greenledger-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "8080:80"
      - "8443:443"
      - "8090:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: greenledger-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: greenledger-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources

volumes:
  postgres_calculator_data:
  postgres_tracker_data:
  postgres_wallet_data:
  postgres_userauth_data:
  postgres_reporting_data:
  postgres_certifier_data:
  redis_data:
  zookeeper_data:
  kafka_data:
  prometheus_data:
  grafana_data:

networks:
  default:
    name: greenledger-network
