# IMPORTANT: This is a template file. 
# Replace all placeholder values with actual secrets before applying.
# DO NOT commit actual secrets to version control.

apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: greenledger-staging
  labels:
    app: greenledger
    environment: staging
type: Opaque
data:
  # Database passwords (base64 encoded)
  # Use: echo -n "your-password" | base64
  calculator-db-password: "REPLACE_WITH_BASE64_ENCODED_PASSWORD"
  tracker-db-password: "REPLACE_WITH_BASE64_ENCODED_PASSWORD"
  wallet-db-password: "REPLACE_WITH_BASE64_ENCODED_PASSWORD"
  userauth-db-password: "REPLACE_WITH_BASE64_ENCODED_PASSWORD"
  reporting-db-password: "REPLACE_WITH_BASE64_ENCODED_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: greenledger-staging
  labels:
    app: greenledger
    environment: staging
type: Opaque
data:
  # JWT secret key (base64 encoded)
  # Generate with: openssl rand -base64 32
  jwt-secret-key: "REPLACE_WITH_BASE64_ENCODED_JWT_SECRET"
---
apiVersion: v1
kind: Secret
metadata:
  name: external-secrets
  namespace: greenledger-staging
  labels:
    app: greenledger
    environment: staging
type: Opaque
data:
  # Redis password (base64 encoded)
  redis-password: "REPLACE_WITH_BASE64_ENCODED_REDIS_PASSWORD"
  
  # Kafka credentials (base64 encoded)
  kafka-username: "REPLACE_WITH_BASE64_ENCODED_KAFKA_USERNAME"
  kafka-password: "REPLACE_WITH_BASE64_ENCODED_KAFKA_PASSWORD"
  
  # Email service API key (base64 encoded)
  email-api-key: "REPLACE_WITH_BASE64_ENCODED_EMAIL_API_KEY"
  
  # Blockchain RPC URL (base64 encoded)
  blockchain-rpc-url: "REPLACE_WITH_BASE64_ENCODED_RPC_URL"
  
  # Blockchain private key for contract interactions (base64 encoded)
  blockchain-private-key: "REPLACE_WITH_BASE64_ENCODED_PRIVATE_KEY"
  
  # External API keys (base64 encoded)
  carbon-api-key: "REPLACE_WITH_BASE64_ENCODED_CARBON_API_KEY"
  weather-api-key: "REPLACE_WITH_BASE64_ENCODED_WEATHER_API_KEY"
---
# Example commands to create secrets manually:
# 
# kubectl create secret generic db-secrets \
#   --from-literal=calculator-db-password=your-calculator-password \
#   --from-literal=tracker-db-password=your-tracker-password \
#   --from-literal=wallet-db-password=your-wallet-password \
#   --from-literal=userauth-db-password=your-userauth-password \
#   --from-literal=reporting-db-password=your-reporting-password \
#   --namespace=greenledger-staging
#
# kubectl create secret generic jwt-secret \
#   --from-literal=jwt-secret-key=$(openssl rand -base64 32) \
#   --namespace=greenledger-staging
#
# kubectl create secret generic external-secrets \
#   --from-literal=redis-password=your-redis-password \
#   --from-literal=kafka-username=your-kafka-username \
#   --from-literal=kafka-password=your-kafka-password \
#   --from-literal=email-api-key=your-sendgrid-api-key \
#   --from-literal=blockchain-rpc-url=https://sepolia.infura.io/v3/your-project-id \
#   --from-literal=blockchain-private-key=your-private-key \
#   --from-literal=carbon-api-key=your-carbon-api-key \
#   --from-literal=weather-api-key=your-weather-api-key \
#   --namespace=greenledger-staging
