apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker-service
  namespace: greenledger-staging
  labels:
    app: greenledger
    service: tracker
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greenledger
      service: tracker
  template:
    metadata:
      labels:
        app: greenledger
        service: tracker
        environment: staging
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: greenledger-service-account
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: tracker
        image: ghcr.io/sloweyyy/greenledger/tracker:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8082
          protocol: TCP
        - name: grpc
          containerPort: 9082
          protocol: TCP
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: LOG_LEVEL
          value: "info"
        - name: HTTP_PORT
          value: "8082"
        - name: GRPC_PORT
          value: "9082"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: greenledger-config
              key: tracker-db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: greenledger-config
              key: tracker-db-port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: greenledger-config
              key: tracker-db-name
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: greenledger-config
              key: tracker-db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: tracker-db-password
        - name: DB_SSLMODE
          value: "require"
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: greenledger-config
              key: redis-host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: greenledger-config
              key: redis-port
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: external-secrets
              key: redis-password
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: greenledger-config
              key: kafka-brokers
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: jwt-secret-key
        - name: CALCULATOR_SERVICE_URL
          value: "calculator-service:9081"
        - name: WALLET_SERVICE_URL
          value: "wallet-service:9083"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: var-run
          mountPath: /var/run
      volumes:
      - name: tmp
        emptyDir: {}
      - name: var-run
        emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tracker-hpa
  namespace: greenledger-staging
  labels:
    app: greenledger
    service: tracker
    environment: staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tracker-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
