apiVersion: v1
kind: Namespace
metadata:
  name: greenledger-staging
  labels:
    name: greenledger-staging
    environment: staging
    app: greenledger
  annotations:
    description: "GreenLedger staging environment"
---
apiVersion: v1
kind: Namespace
metadata:
  name: greenledger-production
  labels:
    name: greenledger-production
    environment: production
    app: greenledger
  annotations:
    description: "GreenLedger production environment"
---
# Resource Quota for Staging
apiVersion: v1
kind: ResourceQuota
metadata:
  name: greenledger-quota
  namespace: greenledger-staging
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "10"
---
# Resource Quota for Production
apiVersion: v1
kind: ResourceQuota
metadata:
  name: greenledger-quota
  namespace: greenledger-production
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "50"
    services: "20"
    persistentvolumeclaims: "20"
---
# Network Policy for Staging
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: greenledger-network-policy
  namespace: greenledger-staging
spec:
  podSelector:
    matchLabels:
      app: greenledger
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: greenledger-staging
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
  - from: []
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 8081
    - protocol: TCP
      port: 8082
    - protocol: TCP
      port: 8083
    - protocol: TCP
      port: 8084
    - protocol: TCP
      port: 8085
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector:
        matchLabels:
          name: greenledger-staging
  - to: []
    ports:
    - protocol: TCP
      port: 5432  # PostgreSQL
    - protocol: TCP
      port: 6379  # Redis
    - protocol: TCP
      port: 9092  # Kafka
    - protocol: TCP
      port: 443   # HTTPS
    - protocol: TCP
      port: 80    # HTTP
---
# Network Policy for Production
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: greenledger-network-policy
  namespace: greenledger-production
spec:
  podSelector:
    matchLabels:
      app: greenledger
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: greenledger-production
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
  - from: []
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 8081
    - protocol: TCP
      port: 8082
    - protocol: TCP
      port: 8083
    - protocol: TCP
      port: 8084
    - protocol: TCP
      port: 8085
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector:
        matchLabels:
          name: greenledger-production
  - to: []
    ports:
    - protocol: TCP
      port: 5432  # PostgreSQL
    - protocol: TCP
      port: 6379  # Redis
    - protocol: TCP
      port: 9092  # Kafka
    - protocol: TCP
      port: 443   # HTTPS
    - protocol: TCP
      port: 80    # HTTP
